services:
  db:
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    image: mysql:8.0
    ports:
    - 3306:3306
    volumes:
    - db_data:/var/lib/mysql
  wordpress:
    container_name: wordpress
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
    image: wordpress:php7.4-apache
    ports:
    - 8080:80
    volumes:
    - wordpress_data:/var/www/html
version: '3.9'
volumes:
  db_data: null
  wordpress_data: null
